__BUSINESS CHALLENGE 1__

Team 7: Dress and Attire

In [106]:
import pandas as pd #importing pandas library to create dataframes and perform the required operations

file = "wedding_cost_data.csv"

wedding_data = pd.read_csv(file) #reading the csv file
wedding_data.head()

,Serial No,functions,vendor_name,budget_level,item_name,price_per_item,quantity,subtotal
0,1,flowers,fresh petals,inexpensive,white flowers,2,465,930
1,2a,venue,fort mason centre for arts and culture,inexpensive,fort mason centre backyard (venue rental fees),7500,1,7500
2,2b,venue,fort mason centre for arts and culture,inexpensive,"cost for insurance, security, coordinator",900,1,900
3,2c,venue,fort mason centre for arts and culture,inexpensive,catering and bar service,6100,1,6100
4,2d,venue,fort mason centre for arts and culture,inexpensive,rentals for table and chair,3200,1,3200

In [107]:
#the budget level for the wedding (i.e., an aggregation of vendor budget levels)
vendor_budget_summary = wedding_data.groupby('vendor_name')['subtotal'].sum().sort_values(ascending=False)
vendor_budget_summary

vendor_name
fort mason centre for arts and culture    18800
the klipptones                             2753
george street photo and video              2545
master fix jewelers                        1448
tina bridal and creations                  1196
swc consultants                            1000
fresh petals                                930
men wearhouse                               428
beauty by pace                              300
mitraartcake                                300
pro digital photos                          270
Name: subtotal, dtype: int64

In [108]:
#the product/service level data
product_service_data = wedding_data[['item_name', 'price_per_item', 'quantity', 'subtotal']].sort_values(by='subtotal', ascending=False)
product_service_data

,item_name,price_per_item,quantity,subtotal
1,fort mason centre backyard (venue rental fees),7500,1,7500
3,catering and bar service,6100,1,6100
4,rentals for table and chair,3200,1,3200
6,package price,2753,1,2753
10,Photo Premier,2545,1,2545
12,embroidered v-neck mermaid wedding gown,1136,1,1136
5,taxes and service charges,1100,1,1100
22,package price,1000,1,1000
0,white flowers,2,465,930
2,"cost for insurance, security, coordinator",900,1,900
8,rings men,649,1,649
7,rings women,649,1,649
21,classic vanilla cake (chiffon),300,1,300
11,ceremony/engagement/wedding day services,300,1,300
20,folded cards (5X7 tri fold),2,135,270
14,JOE Joseph Abboud Slim Fit Linen Blend Suit Se...,200,1,200
9,bracelet women,150,1,150
19,Moretti Stardust crystal formal loafers (Black),80,1,80
13,crystal drop earrings,60,1,60
16,Ben Sherman Slim Fit Dobby Dress Shirt (White),60,1,60
17,Paisley & Gray fit suit separates pants (White),40,1,40
15,Egara pre-tied bow tie (Black),35,1,35
18,Egara Ankle Compression Socks (White),13,1,13

In [109]:
#department-level price summary (i.e., a department-level breakdown)
department_level_breakdown = wedding_data.groupby('functions')['subtotal'].sum().sort_values(ascending = False)
department_level_breakdown

functions
venue                  18800
music                   2753
photo and video         2545
jewelry                 1448
dress atire - bride     1196
wedding planners        1000
flowers                  930
dress atire - groom      428
cake                     300
hair and makeup          300
invitations              270
Name: subtotal, dtype: int64

In [110]:
#total price of the wedding
total_price = wedding_data['subtotal'].sum()
total_price

29970

In [111]:
# Defining functions to format each section of the wedding cost breakdown

def format_vendor_budget_summary(vendor_budget):
    formatted_summary = "Vendor Budget Summary (prices in USD): \n\n" + \
                        "\n".join([f"{vendor}: {subtotal}" for vendor, subtotal in vendor_budget.items()])
    return formatted_summary

def format_product_service_data(product_service):
    formatted_data = "Product/Service Level Data (prices in USD): \n\n" + product_service.to_string(index=False)
    return formatted_data

def format_department_level_breakdown(department_breakdown):
    formatted_breakdown = "Department-Level Price Summary (prices in USD): \n\n" + \
                          "\n".join([f"{department}: {subtotal}" for department, subtotal in department_breakdown.items()])
    return formatted_breakdown

def format_total_price(total):
    return f"Total Price for the Wedding: ${total}"

# Applying the formatting functions to create the wedding cost breakdown

formatted_vendor_budget_summary = format_vendor_budget_summary(vendor_budget_summary)
formatted_product_service_data = format_product_service_data(product_service_data)
formatted_department_level_breakdown = format_department_level_breakdown(department_level_breakdown)
formatted_total_price = format_total_price(total_price)

# Combining all parts into a final output string
formatted_wedding_cost_breakdown = (
    "Wedding Cost Breakdown\n\n"
    f"{formatted_vendor_budget_summary}\n\n"
    f"{formatted_product_service_data}\n\n"
    f"{formatted_department_level_breakdown}\n\n"
    f"{formatted_total_price}\n"
)

print(formatted_wedding_cost_breakdown)

Wedding Cost Breakdown

Vendor Budget Summary (prices in USD):

fort mason centre for arts and culture: 18800
the klipptones: 2753
george street photo and video: 2545
master fix jewelers: 1448
tina bridal and creations: 1196
swc consultants: 1000
fresh petals: 930
men wearhouse: 428
beauty by pace: 300
mitraartcake: 300
pro digital photos: 270

Product/Service Level Data (prices in USD):

                                                         item_name  price_per_item  quantity  subtotal
                    fort mason centre backyard (venue rental fees)            7500         1      7500
                                          catering and bar service            6100         1      6100
                                       rentals for table and chair            3200         1      3200
                                                     package price            2753         1      2753
                                                     Photo Premier            2545         1      2545
                           embroidered v-neck mermaid wedding gown            1136         1      1136
                                         taxes and service charges            1100         1      1100
                                                     package price            1000         1      1000
                                                     white flowers               2       465       930
                        cost for insurance, security, coordinator              900         1       900
                                                         rings men             649         1       649
                                                       rings women             649         1       649
                                    classic vanilla cake (chiffon)             300         1       300
                          ceremony/engagement/wedding day services             300         1       300
                                       folded cards (5X7 tri fold)               2       135       270
JOE Joseph Abboud Slim Fit Linen Blend Suit Separates Coat (White)             200         1       200
                                                    bracelet women             150         1       150
                   Moretti Stardust crystal formal loafers (Black)              80         1        80
                                             crystal drop earrings              60         1        60
                    Ben Sherman Slim Fit Dobby Dress Shirt (White)              60         1        60
                   Paisley & Gray fit suit separates pants (White)              40         1        40
                                    Egara pre-tied bow tie (Black)              35         1        35
                             Egara Ankle Compression Socks (White)              13         1        13

Department-Level Price Summary (prices in USD):

venue: 18800
music: 2753
photo and video: 2545
jewelry: 1448
dress atire - bride: 1196
wedding planners: 1000
flowers: 930
dress atire - groom: 428
cake: 300
hair and makeup: 300
invitations: 270

Total Price for the Wedding: $29970